import { jsx as _jsx } from "react/jsx-runtime";
import * as React from 'react';
import { cn } from '@/lib/utils';
export const Card = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('relative rounded-2xl border border-border/70 bg-card/90 text-card-foreground shadow-[0_2px_4px_-2px_hsl(220_40%_20%/0.08),0_12px_30px_-16px_hsl(220_40%_20%/0.18)] backdrop-blur-sm transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_4px_6px_-2px_hsl(220_40%_20%/0.1),0_20px_40px_-18px_hsl(220_40%_20%/0.25)]', className), ...props })));
Card.displayName = 'Card';
export const CardHeader = ({ className, ...props }) => (_jsx("div", { className: cn('flex flex-col space-y-1.5 p-5', className), ...props }));
export const CardTitle = ({ className, ...props }) => (_jsx("h3", { className: cn('font-display text-lg font-semibold leading-none tracking-tight', className), ...props }));
export const CardDescription = ({ className, ...props }) => (_jsx("p", { className: cn('text-sm text-muted-foreground', className), ...props }));
export const CardContent = ({ className, ...props }) => (_jsx("div", { className: cn('p-5 pt-0', className), ...props }));
export const CardFooter = ({ className, ...props }) => (_jsx("div", { className: cn('flex items-center p-5 pt-0', className), ...props }));
